#!/bin/bash

show_monitor() {
	for pid in $(pgrep avpinput); do
		echo "PROCESS $pid"
		viu -h 20 "/tmp/avpinput_$pid.jpg"
		i=1
		echo -n "AUDIO CH "
		for ch in $(cat "/tmp/avpinput_$pid.peak"); do echo -n "$i:${ch}dB "; i=$(($i+1)); done
		echo
		echo
	done
}

loop() {
	while true; do clear; show_monitor; sleep 5; done
}

[ "$1" = "-c" ] && loop || show_monitor
